import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.scss";
import Provider from "@/utils/Provider";
import { SpeedInsights } from '@vercel/speed-insights/next';
const montSerrat = Montserrat({ subsets: ["latin"], display:"swap" });

export const metadata: Metadata = {
  title: "MKS Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montSerrat.className}>
        <Provider>{children}</Provider>
        <SpeedInsights/>
      </body>
    </html>
  );
}
