import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import Provider from "@/utils/Provider";

const montSerrat = Montserrat({ subsets: ["latin"], display:"swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montSerrat.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
